Repository dassana-io/web-utils, pull requests merged in 2021-10, with the labels that each got.

#114 feat #113 - Refac handleAjaxErrors to handle errors that don't have response
  package-lock.json
  package.json
  src/__tests__/apiUtils.test.ts
  src/apiUtils.ts
Labels: feature, patch

#116 chore #115 - Extract out useInView to use across repos
  package.json
  src/hookUtils.ts
Labels: chore, patch

#118 chore #117 - Update handleAjaxErrors
  package-lock.json
  package.json
  src/__tests__/apiUtils.test.ts
  src/apiUtils.ts
Labels: chore, patch

#120 Fix #119 - Cancelled requests being thrown as errors
  package-lock.json
  package.json
  src/apiUtils.ts
Labels: bug, patch
