Repository dassana-io/web-utils, pull requests merged in 2022-05, with the labels that each got.

#179 chore #178 - Update services enum
  package.json
  src/types.ts
Labels: chore, patch

#180 chore #178 - Update notification rule service enum
  package.json
  src/types.ts
Labels: chore, patch

#182 enhancement #181 - Add visualize to services enum
  package-lock.json
  package.json
  src/types.ts
Labels: enhancement, patch

#184 enhancement #183 - Display entire response in error snackbar
  package-lock.json
  package.json
  src/apiUtils.ts
Labels: enhancement, patch

#186 enhancement #185 - Pluralize fn
  package-lock.json
  package.json
  src/generalUtils.ts
Labels: enhancement, patch

#188 fix #187 - Update Services enum
  package-lock.json
  package.json
  src/types.ts
Labels: bug, patch

#190 enhancement #189 - Add Billing to Services enum
  package-lock.json
  package.json
  src/types.ts
Labels: enhancement, patch
