Repository dassana-io/web-utils, pull requests merged in 2022-06, with the labels that each got.

#192 fix #191 - Fix convertEpochToUserTimezone
  package-lock.json
  package.json
  src/timeUtils.ts
Labels: bug, patch

#196 fix #195 - Fix fns from useCancelRequest throwing infinite loops
  package-lock.json
  package.json
  src/apiUtils.ts
Labels: bug, patch

#198 enhancement #197 - Add useHoverState fn
  package-lock.json
  package.json
  src/generalUtils.ts
Labels: enhancement, patch

#200 enhancement #199 - Currency formatter
  package-lock.json
  package.json
  src/generalUtils.ts
Labels: enhancement, patch

#202 fix #201 - Fix package breaking builds when imported into web-charts
  package.json
  rollup.config.ts
Labels: bug, patch

#203 fix #201 - Fix web-charts build
  package.json
  rollup.config.ts
Labels: bug, patch

#204 fix #201 - Remove unnecessary rollup config setting
  package.json
  rollup.config.ts
Labels: bug, patch

#206 feat #205 - removeFromArrByIdx util
  package-lock.json
  package.json
  rollup.config.ts
  src/__tests__/generalUtils.test.ts
  src/generalUtils.ts
Labels: feature, patch

#208 enhancement #207 - Byte formatter
  package-lock.json
  package.json
  rollup.config.ts
  src/generalUtils.ts
Labels: enhancement, patch
