Repository dassana-io/web-utils, pull requests merged in 2022-03, with the labels that each got.

#154 Add fn that gets app environment
  package-lock.json
  package.json
  src/generalUtils.ts
Labels: enhancement, patch

#155 fix #153 - getAppEnv util fn
  package-lock.json
  package.json
  src/generalUtils.ts
Labels: bug, patch

#157 enhancement #156 - Export enum for app routes
  package-lock.json
  package.json
  src/types.ts
Labels: enhancement, patch

#159 feat #158 - Util to build browser url
  package.json
  src/__tests__/generalUtils.test.ts
  src/generalUtils.ts
Labels: feature, patch

#162 feat #161 - Add custom hook to return remaining container height
  package-lock.json
  package.json
  src/apiUtils.ts
  src/hookUtils.ts
Labels: feature, patch
