Repository dassana-io/web-utils, pull requests merged in 2022-04, with the labels that each got.

#164 feat #163 - useDebounce hook
  package-lock.json
  package.json
  src/__tests__/hookUtils/index.test.ts
  src/hookUtils.ts
Labels: feature, patch

#166 Add fn for guessing user's timezone
  package-lock.json
  package.json
  src/timeUtils.ts
Labels: enhancement, patch

#168 chore #167 - Profile codegen
  codegen.js
  package.json
Labels: chore, patch

#171 enhancement #170 - Refactor timezone utils
  package-lock.json
  package.json
  src/timeUtils.ts
Labels: enhancement, patch

#173 enhancement #172 - Add email regex
  package-lock.json
  package.json
  src/constants.ts
Labels: enhancement, patch

#175 fix #174 - [useShortcut] Add blur event to clear first key pressed
  package-lock.json
  package.json
  src/hookUtils.ts
Labels: bug, patch

#177 enhancement #176 - Allow more than 2 keys to be passed to getModifierKeys
  package.json
  src/hookUtils.ts
Labels: enhancement, patch
