Repository dassana-io/web-utils, pull requests merged in 2024-09, with the labels that each got.

#302 chore #301 - Add $assetSources to FilterKeys
  package-lock.json
  package.json
  src/types.ts
Labels: chore, patch

#303 chore #301 - Add $assetDeleted to FilterKeys
  package-lock.json
  package.json
  src/types.ts
Labels: chore, patch

#305 chore #304 - Bump package versions
  package-lock.json
  package.json
  rollup.config.ts
  src/apiUtils.ts
  src/generalUtils.ts
  src/timeUtils.ts
Labels: chore, minor

#307 chore #306 - "os" filter key label incorrect processing
  package-lock.json
  package.json
  src/constants.ts
Labels: bug, patch

#308 chore #294 - Add missing filter keys
  package-lock.json
  package.json
  src/constants.ts
  src/types.ts
Labels: chore, patch

#309 chore #278 - Fix package vulnerabilities
  package-lock.json
  package.json
  rollup.config.ts
  src/api/preferences/configObject.ts
  tsconfig.json
Labels: chore, patch

#310 bugfix #278 - Fix missing declaration file
  package-lock.json
  package.json
  rollup.config.ts
  vite.config.js
Labels: bug, patch

#314 bugfix #278 - Fix missing types
  package-lock.json
  package.json
  rollup.config.ts
Labels: bug, patch

#315 bugfix #278 - Fix types in packages
  package-lock.json
  package.json
  rollup.config.ts
  src/react-app-env.d.ts
Labels: bug, patch

#316 bugfix #278 - Move react to peer dependencies
  package-lock.json
  package.json
  rollup.config.ts
  setupTests.ts
  src/setupTests.ts
  tsconfig.json
Labels: bug, patch

#317 bugfix #278 - Update peer dependencies
  package-lock.json
  package.json
Labels: bug, patch

#318 bugfix #278 - Add externals array to rollup
  package-lock.json
  package.json
  rollup.config.ts
Labels: bug, patch
